# Generated by Django 4.2.5 on 2023-09-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SS', 'Sports Shirts'), ('RS', 'Regular Shirts'), ('TR', 'Trousers'), ('ST', 'Sports Trouser')], max_length=2),
        ),
    ]
