FROM python:3.10-slim-buster

ENV PYTHONBUFFERED=1

WORKDIR /app            # /app/akira

COPY requirements.txt requirements.txt 

RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8000

CMD gunicorn akira.wsgi:application --bind 0.0.0.0:8000
