version: "3.10"
services:
  app:
   build: .
   volumes:
     - .:/app
   ports:
     - 8000:8000
   image: application:app
   container_name: app_container
   command: gunicorn akira.wsgi:application --bind 0.0.0.0:8000
